export const sozluk = {
  en: {
    loginIdentifierPlaceholder: "Username or email",
    registerUsernamePlaceholder: "Username",
    passPlaceholder: "Password",
    connectBtn: "Login",
    registerBtn: "Register Account",
    emailPlaceholder: "Email",
    emailMissing: "Please enter an email address.",
    invalidEmail: "Please enter a valid email address.",
    switchToReg: "Need an account? Register here.",
    switchToLogin: "Already have an account? Login here.",
    srvIp: "Server IP",
    srvUser: "Server User (e.g. root)",
    srvPass: "Server Password",
    folder: "Isolated Folder (e.g. /PionterCloud)",
    currentPath: "Current Path:",
    upFolder: "Up",
    loading: "Processing...",
    emptyFolder: "This folder is empty.",
    dragDrop: "Drag and drop files here",
    orSelect: "or select from your computer",
    selectBtn: "Select File",
    regSuccess: "Registration successful! You can now login.",
    regFail: "Registration failed. Username or email might be taken.",
    myServers: "My Servers",
    serversDraftInfo: "Add your first server by clicking the box below.",
    addServer: "Add Server",
    noServersYet: "No servers added yet.",
    noServersInfo: "In the next task, we will make this form save a server.",
    newServer: "Add New Server",
    serverNickname: "Server Nickname",
    sshUser: "SSH User",
    sshPort: "SSH Port",
    connectWithPassword: "Connect with password",
    connectWithKey: "Connect with SSH key",
    isolatedFolder: "Isolated Folder",
    sshPrivateKey: "SSH Private Key",
    cancel: "Cancel",
    save: "Save",
    saveLater: "We will make the save action work in the next task.",
    loginMissing: "Please enter username and password!",
    selectedServer: "Selected Server",
    backToServers: "Back to Servers",
    newFolderPlaceholder: "New folder name",
    createFolder: "Create Folder",
    deleteItem: "Delete",
    deleteConfirm: "Are you sure you want to delete this item?",
    deleteFailed: "Delete failed.",
    renameItem: "Rename",
    renamePrompt: "Enter the new name:",
    renameFailed: "Rename failed.",
    moveItem: "Move",
    moveFailed: "Move failed.",
    moveSuccess: "Moved successfully.",
    dropHereToMove: "Drop here to move or upload",
    cannotMoveFolderIntoItself: "A folder cannot be moved into itself.",
    folderContentsPreview: "Folder contents",
    loadingFolderContents: "Loading folder contents...",
    homeFolder: "Home",
    searchPlaceholder: "Search in current folder...",
    noSearchResults: "No matching files or folders found.",
    uploadSuccess: "File uploaded successfully.",
    uploadFailed: "Upload failed.",
    folderCreateSuccess: "Folder created successfully.",
    folderCreateFailed: "Folder could not be created.",
    selectServerFirst: "You must select a server first.",
    invalidFileName: "File name cannot include /, \\, ⁄ or ...",
    folderNameEmpty: "Folder name cannot be empty.",
    invalidFolderName: "Folder name cannot include /, \\, ⁄ or ...",
    invalidTargetPath: "Target path cannot include \\, ⁄ or ...",
    alreadyInThisFolder: "This item is already in that folder.",
    renameModalTitle: "Rename Item",
    newNamePlaceholder: "New name",
    confirmRename: "Rename",
    moveModalTitle: "Move Item",
    targetPathEmpty: "Target folder path cannot be empty.",
    deleteModalTitle: "Delete Item",
    deleteModalText: "Are you sure you want to delete this item?",
    confirmDelete: "Delete",
    serverRequiredFields: "Please fill the required fields.",
    serverPasswordRequired: "Please enter the server password.",
    sshKeyRequired: "Please enter the SSH private key.",
    serverSaveFailed: "Server could not be saved.",
    serverSaveSuccess: "Server saved successfully.",
    invalidServerPort: "SSH port must be a number between 1 and 65535.",
    invalidIsolatedFolder: "Isolated folder must start with /.",
    loadingFiles: "Loading files...",
    uploadingFile: "Uploading file...",
    creatingFolder: "Creating folder...",
    deletingItem: "Deleting item...",
    renamingItem: "Renaming item...",
    movingItem: "Moving item...",
    downloadingFile: "Downloading file...",
    savingServer: "Checking connection and saving server...",
    loadingServers: "Loading servers...",
    registeringAccount: "Creating account...",
    authTitle: "Your own cloud, on your own server.",
    authSubtitle:
      "Add your server and manage your files through a clean web interface.",
    loginTitle: "Welcome back",
    registerTitle: "Create your account",
    loginInfo: "Login with your username or email and password.",
    registerInfo: "Create a Pionter account to start adding your servers.",
    confirmMoveHere: "Move Here",
    currentMoveTarget: "Current target",
    deleteServer: "Delete Server",
    deleteServerTitle: "Delete Server",
    deleteServerText:
      "This will remove the server from PionterCloud. Files on the actual server will not be deleted.",
    deleteServerFailed: "Server could not be deleted.",
    deleteServerSuccess: "Server deleted successfully.",
    deletingServer: "Deleting server...",
    editServer: "Edit",
    editServerTitle: "Edit Server",
    serverCredentialsOptional:
      "Leave the password or SSH key empty to keep the current saved credential.",
    saveServerChanges: "Save Changes",
    serverUpdateSuccess: "Server updated successfully.",
    serverUpdateFailed: "Server could not be updated.",
    updatingServer: "Checking connection and updating server...",
    pinServer: "Pin",
    unpinServer: "Unpin",
    serverPinFailed: "Server pin status could not be updated.",
    pinnedServer: "Pinned",
    testConnection: "Test Connection",
    testingConnection: "Testing connection...",
    connectionTestSuccess: "Connection test successful.",
    connectionTestFailed: "Connection test failed.",
    loggingIn: "Logging in...",
    logout: "Logout",
    loggingOut: "Logging out...",
    logoutSuccess: "Logged out successfully.",
    logoutFailed: "Logout failed.",
    sessionExpired: "Your session has expired. Please log in again.",
    uploadProgress: "Upload",
    multiUploadSuccess: "Files uploaded successfully.",
    selectedItems: "item(s) selected",
    clearSelection: "Clear selection",
    selectItem: "Select item",
    unselectItem: "Unselect item",
    deleteSelected: "Delete selected",
    deleteSelectedTitle: "Delete selected items",
    deleteSelectedConfirmText:
      "Are you sure you want to delete selected item(s)?",
    deletingSelectedItems: "Deleting selected items...",
    selectedItemsDeleted: "Selected items deleted.",
    bulkDeleteFailed: "Selected items could not be deleted.",
    selectListed: "Select listed",
    upload: "Upload",
    dropFilesToUpload: "Drop files to upload",
    releaseMouseToUpload: "Release to start uploading",
    newFolder: "New folder",
    newFolderTitle: "Create new folder",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    darkMode: "Dark mode",
    lightMode: "Light mode",
    servers: "Servers",
    manageServers: "Manage servers",
    serverPreview: "Current preview",
    noPreview: "No preview yet",
    openSidebar: "Open sidebar",
    closeSidebar: "Close sidebar",
    moveSelected: "Move selected",
    bulkMoveModalTitle: "Move selected items",
    movingSelectedItems: "Moving selected items",
    selectedItemsMoved: "Selected items moved successfully.",
    bulkMoveFailed: "Selected items could not be moved.",
    selectedItemsPreview: "Selected items",
    moreItems: "more item(s)",
    serverStatus: "Server Status",
    refreshStats: "Refresh",
    loadingStats: "Loading stats...",
    statsLoadFailed: "Server stats could not be loaded.",
    cpuUsage: "CPU",
    ramUsage: "RAM",
    diskUsage: "Disk",
    uptime: "Uptime",
    loadAverage: "Load avg",
    used: "used",
    serverReachable: "SSH OK",
    lastUpdated: "Last updated",
    loadingPreview: "Loading preview...",
    previewLoadFailed: "File preview could not be loaded.",
    previewNotAvailable: "Preview is not available for this file yet.",
    filePreview: "File Preview",
    downloadFile: "Download",
    close: "Close",
    pdfPreviewNotAvailable:
      "PDF preview is not available yet. You can download the file instead.",
    moveSuccess: "Moved successfully.",
    dropHereToMove: "Drop here to move",
    cannotMoveFolderIntoItself: "A folder cannot be moved into itself.",
    editFile: "Edit",
    saveFile: "Save",
    savingFile: "Saving...",
    cancelEdit: "Cancel Edit",
    fileSaveSuccess: "File saved successfully.",
    fileSaveFailed: "File could not be saved.",
    unsavedChangesConfirm:
      "You have unsaved changes. Are you sure you want to close without saving?",
    unsavedChanges: "Unsaved changes",
    saveShortcutHint: "Press Ctrl+S / Cmd+S to save",
    permissionDenied:
      "The SSH user does not have permission for this operation.",
    filesLoadFailed: "Files could not be loaded.",
    downloadFailed: "File could not be downloaded.",
    shareItem: "Share",
    shareFileTitle: "Share file",
    shareDuration: "Link duration",
    shareDuration1h: "1 hour",
    shareDuration1d: "1 day",
    shareDuration1w: "1 week",
    shareDuration1m: "1 month",
    shareDuration1y: "1 year",
    shareDurationUnlimited: "Unlimited",
    shareLinkHelp:
      "Anyone with this link can download this file until the link expires or is revoked.",
    createShareLink: "Create link",
    creatingShareLink: "Creating link...",
    shareLinkCreated: "Share link created.",
    shareLinkCreateFailed: "Share link could not be created.",
    sharedLink: "Share link",
    copyShareLink: "Copy",
    shareLinkCopied: "Share link copied.",
    shareOnlyFiles: "Only files can be shared for now.",
    openFileMenu: "Open file menu",
    manageShareLinks: "Share links",
    manageShareLinksHelp:
      "View and revoke your active, expired, and revoked share links.",
    loadingShareLinks: "Loading share links...",
    shareLinksLoadFailed: "Share links could not be loaded.",
    noShareLinks: "No share links yet.",
    shareStatusActive: "Active",
    shareStatusExpired: "Expired",
    shareStatusRevoked: "Revoked",
    revokeShare: "Revoke",
    revokingShare: "Revoking...",
    shareRevoked: "Share link revoked.",
    shareRevokeFailed: "Share link could not be revoked.",
    revokeShareTitle: "Revoke share link",
    revokeShareText:
      "This share link will stop working immediately. This action cannot be undone.",
    revokeShareConfirmButton: "Revoke link",
    refreshShareLinks: "Refresh",
    createdAt: "Created",
    path: "Path",
  },
  tr: {
    loginIdentifierPlaceholder: "Kullanıcı adı veya e-posta",
    registerUsernamePlaceholder: "Kullanıcı adı",
    passPlaceholder: "Şifre",
    connectBtn: "Giriş Yap",
    registerBtn: "Hesap Oluştur",
    emailPlaceholder: "E-posta",
    emailMissing: "Lütfen e-posta adresi gir.",
    invalidEmail: "Lütfen geçerli bir e-posta adresi gir.",
    switchToReg: "Hesabın yok mu? Buradan kayıt ol.",
    switchToLogin: "Zaten hesabın var mı? Buradan giriş yap.",
    srvIp: "Sunucu IP",
    srvUser: "Sunucu Kullanıcısı (Örn: root)",
    srvPass: "Sunucu Şifresi",
    folder: "İzole Klasör (Örn: /PionterCloud)",
    currentPath: "Mevcut Konum:",
    upFolder: "Üst Klasör",
    loading: "İşlem yapılıyor...",
    emptyFolder: "Bu klasör boş.",
    dragDrop: "Dosyaları buraya sürükleyin",
    orSelect: "veya bilgisayarınızdan seçin",
    selectBtn: "Dosya Seç",
    regSuccess: "Kayıt başarılı! Şimdi giriş yapabilirsiniz.",
    regFail: "Kayıt başarısız. Kullanıcı adı veya e-posta alınmış olabilir.",
    myServers: "Sunucularım",
    serversDraftInfo: "İlk sunucunu aşağıdaki kutuya tıklayarak ekle.",
    addServer: "Sunucu Ekle",
    noServersYet: "Henüz sunucu eklenmedi.",
    noServersInfo:
      "Bir sonraki görevde bu formun sunucu kaydetmesini sağlayacağız.",
    newServer: "Yeni Sunucu Ekle",
    serverNickname: "Sunucu Takma Adı",
    sshUser: "SSH Kullanıcısı",
    sshPort: "SSH Portu",
    connectWithPassword: "Şifre ile bağlan",
    connectWithKey: "SSH Key ile bağlan",
    isolatedFolder: "İzole Klasör",
    sshPrivateKey: "SSH Private Key",
    cancel: "Vazgeç",
    save: "Kaydet",
    saveLater: "Kaydetme işlemini bir sonraki görevde yapacağız.",
    loginMissing: "Kullanıcı adı ve şifre gir!",
    selectedServer: "Seçili Sunucu",
    backToServers: "Sunuculara Dön",
    newFolderPlaceholder: "Yeni klasör adı",
    createFolder: "Klasör Oluştur",
    deleteItem: "Sil",
    deleteConfirm: "Bu öğeyi silmek istediğine emin misin?",
    deleteFailed: "Silme başarısız.",
    renameItem: "Yeniden Adlandır",
    renamePrompt: "Yeni adı gir:",
    renameFailed: "Yeniden adlandırma başarısız.",
    moveItem: "Taşı",
    moveFailed: "Taşıma başarısız.",
    moveSuccess: "Taşıma başarılı.",
    dropHereToMove: "Taşımak veya yüklemek için buraya bırak",
    cannotMoveFolderIntoItself: "Bir klasör kendi içine taşınamaz.",
    folderContentsPreview: "Klasör içeriği",
    loadingFolderContents: "Klasör içeriği yükleniyor...",
    homeFolder: "Home",
    searchPlaceholder: "Mevcut klasörde ara...",
    noSearchResults: "Eşleşen dosya veya klasör bulunamadı.",
    uploadSuccess: "Dosya başarıyla yüklendi.",
    uploadFailed: "Dosya yükleme başarısız.",
    folderCreateSuccess: "Klasör başarıyla oluşturuldu.",
    folderCreateFailed: "Klasör oluşturulamadı.",
    selectServerFirst: "Önce sunucu seçmelisin.",
    invalidFileName: "Dosya adında /, \\, ⁄ veya .. kullanılamaz.",
    folderNameEmpty: "Klasör adı boş olamaz.",
    invalidFolderName: "Klasör adında /, \\, ⁄ veya .. kullanılamaz.",
    invalidTargetPath: "Hedef yolda \\, ⁄ veya .. kullanılamaz.",
    alreadyInThisFolder: "Bu öğe zaten o klasörde.",
    renameModalTitle: "Yeniden Adlandır",
    newNamePlaceholder: "Yeni ad",
    confirmRename: "Yeniden Adlandır",
    moveModalTitle: "Taşı",
    targetPathEmpty: "Hedef klasör yolu boş olamaz.",
    deleteModalTitle: "Sil",
    deleteModalText: "Bu öğeyi silmek istediğine emin misin?",
    confirmDelete: "Sil",
    serverRequiredFields: "Lütfen zorunlu alanları doldur.",
    serverPasswordRequired: "Lütfen sunucu şifresini gir.",
    sshKeyRequired: "Lütfen SSH private key gir.",
    serverSaveFailed: "Sunucu kaydedilemedi.",
    serverSaveSuccess: "Sunucu başarıyla kaydedildi.",
    invalidServerPort: "SSH portu 1 ile 65535 arasında bir sayı olmalı.",
    invalidIsolatedFolder: "İzole klasör / ile başlamalı.",
    loadingFiles: "Dosyalar yükleniyor...",
    uploadingFile: "Dosya yükleniyor...",
    creatingFolder: "Klasör oluşturuluyor...",
    deletingItem: "Öğe siliniyor...",
    renamingItem: "Yeniden adlandırılıyor...",
    movingItem: "Öğe taşınıyor...",
    downloadingFile: "Dosya indiriliyor...",
    savingServer: "Bağlantı kontrol ediliyor ve sunucu kaydediliyor...",
    loadingServers: "Sunucular yükleniyor...",
    registeringAccount: "Hesap oluşturuluyor...",
    authTitle: "Kendi sunucun, kendi bulutun.",
    authSubtitle: "Sunucunu ekle ve dosyalarını sade bir web arayüzüyle yönet.",
    loginTitle: "Tekrar hoş geldin",
    registerTitle: "Hesabını oluştur",
    loginInfo: "Kullanıcı adın veya e-postan ve şifrenle giriş yap.",
    registerInfo: "Sunucularını eklemeye başlamak için Pionter hesabı oluştur.",
    confirmMoveHere: "Buraya Taşı",
    currentMoveTarget: "Geçerli hedef",
    deleteServer: "Sunucuyu Sil",
    deleteServerTitle: "Sunucuyu Sil",
    deleteServerText:
      "Bu işlem sunucuyu PionterCloud listesinden kaldırır. Gerçek sunucudaki dosyalar silinmez.",
    deleteServerFailed: "Sunucu silinemedi.",
    deleteServerSuccess: "Sunucu başarıyla silindi.",
    deletingServer: "Sunucu siliniyor...",
    editServer: "Düzenle",
    editServerTitle: "Sunucuyu Düzenle",
    serverCredentialsOptional:
      "Kayıtlı bilgiyi korumak için sunucu şifresini veya SSH key alanını boş bırakabilirsin.",
    saveServerChanges: "Değişiklikleri Kaydet",
    serverUpdateSuccess: "Sunucu başarıyla güncellendi.",
    serverUpdateFailed: "Sunucu güncellenemedi.",
    updatingServer: "Bağlantı kontrol ediliyor ve sunucu güncelleniyor...",
    pinServer: "Sabitle",
    unpinServer: "Kaldır",
    serverPinFailed: "Sunucu sabitleme durumu güncellenemedi.",
    pinnedServer: "Sabitli",
    testConnection: "Bağlantıyı Test Et",
    testingConnection: "Bağlantı test ediliyor...",
    connectionTestSuccess: "Bağlantı testi başarılı.",
    connectionTestFailed: "Bağlantı testi başarısız.",
    loggingIn: "Giriş yapılıyor...",
    logout: "Çıkış Yap",
    loggingOut: "Çıkış yapılıyor...",
    logoutSuccess: "Çıkış yapıldı.",
    logoutFailed: "Çıkış yapılamadı.",
    sessionExpired: "Oturum süren doldu. Lütfen tekrar giriş yap.",
    uploadProgress: "Yükleme",
    multiUploadSuccess: "Dosyalar yüklendi.",
    selectedItems: "öğe seçildi",
    clearSelection: "Seçimi temizle",
    selectItem: "Öğeyi seç",
    unselectItem: "Seçimi kaldır",
    deleteSelected: "Seçilenleri sil",
    deleteSelectedTitle: "Seçili öğeleri sil",
    deleteSelectedConfirmText: "Seçili öğeleri silmek istediğine emin misin?",
    deletingSelectedItems: "Seçili öğeler siliniyor...",
    selectedItemsDeleted: "Seçili öğeler silindi.",
    bulkDeleteFailed: "Seçili öğeler silinemedi.",
    selectListed: "Listelenenleri seç",
    upload: "Yükle",
    dropFilesToUpload: "Yüklemek için dosyaları bırak",
    releaseMouseToUpload: "Yüklemeyi başlatmak için bırak",
    newFolder: "Yeni klasör",
    newFolderTitle: "Yeni klasör oluştur",
    settings: "Ayarlar",
    language: "Dil",
    theme: "Tema",
    darkMode: "Koyu mod",
    lightMode: "Açık mod",
    servers: "Sunucular",
    manageServers: "Sunucuları yönet",
    serverPreview: "Mevcut önizleme",
    noPreview: "Henüz önizleme yok",
    openSidebar: "Kenar çubuğunu aç",
    closeSidebar: "Kenar çubuğunu kapat",
    moveSelected: "Seçilenleri taşı",
    bulkMoveModalTitle: "Seçili öğeleri taşı",
    movingSelectedItems: "Seçili öğeler taşınıyor",
    selectedItemsMoved: "Seçili öğeler başarıyla taşındı.",
    bulkMoveFailed: "Seçili öğeler taşınamadı.",
    selectedItemsPreview: "Seçili öğeler",
    moreItems: "öğe daha",
    serverStatus: "Sunucu Durumu",
    refreshStats: "Yenile",
    loadingStats: "Bilgiler yükleniyor...",
    statsLoadFailed: "Sunucu bilgileri alınamadı.",
    cpuUsage: "CPU",
    ramUsage: "RAM",
    diskUsage: "Disk",
    uptime: "Çalışma süresi",
    loadAverage: "Yük ortalaması",
    used: "kullanılıyor",
    serverReachable: "SSH OK",
    lastUpdated: "Son güncelleme",
    loadingPreview: "Önizleme yükleniyor...",
    previewLoadFailed: "Dosya önizlemesi alınamadı.",
    previewNotAvailable: "Bu dosya için önizleme henüz kullanılamıyor.",
    filePreview: "Dosya Önizleme",
    downloadFile: "İndir",
    close: "Kapat",
    pdfPreviewNotAvailable:
      "PDF önizleme henüz kullanılamıyor. Dosyayı indirebilirsin.",
    moveSuccess: "Taşıma başarılı.",
    dropHereToMove: "Taşımak için buraya bırak",
    cannotMoveFolderIntoItself: "Bir klasör kendi içine taşınamaz.",
    editFile: "Düzenle",
    saveFile: "Kaydet",
    savingFile: "Kaydediliyor...",
    cancelEdit: "Düzenlemeyi İptal Et",
    fileSaveSuccess: "Dosya başarıyla kaydedildi.",
    fileSaveFailed: "Dosya kaydedilemedi.",
    unsavedChangesConfirm:
      "Kaydedilmemiş değişikliklerin var. Kaydetmeden kapatmak istediğine emin misin?",
    unsavedChanges: "Kaydedilmemiş değişiklik var",
    saveShortcutHint: "Kaydetmek için Ctrl+S / Cmd+S",
    permissionDenied: "Bu işlem için SSH kullanıcısının yetkisi yok.",
    filesLoadFailed: "Dosyalar getirilemedi.",
    downloadFailed: "Dosya indirilemedi.",
    shareItem: "Paylaş",
    shareFileTitle: "Dosya paylaş",
    shareDuration: "Link süresi",
    shareDuration1h: "1 saat",
    shareDuration1d: "1 gün",
    shareDuration1w: "1 hafta",
    shareDuration1m: "1 ay",
    shareDuration1y: "1 yıl",
    shareDurationUnlimited: "Süresiz",
    shareLinkHelp:
      "Bu linke sahip olan herkes, link süresi dolana veya link iptal edilene kadar bu dosyayı indirebilir.",
    createShareLink: "Link oluştur",
    creatingShareLink: "Link oluşturuluyor...",
    shareLinkCreated: "Paylaşım linki oluşturuldu.",
    shareLinkCreateFailed: "Paylaşım linki oluşturulamadı.",
    sharedLink: "Paylaşım linki",
    copyShareLink: "Kopyala",
    shareLinkCopied: "Paylaşım linki kopyalandı.",
    shareOnlyFiles: "Şimdilik sadece dosyalar paylaşılabilir.",
    openFileMenu: "Dosya menüsünü aç",
    manageShareLinks: "Paylaşım linkleri",
    manageShareLinksHelp:
      "Aktif, süresi dolmuş ve iptal edilmiş paylaşım linklerini görüntüle ve iptal et.",
    loadingShareLinks: "Paylaşım linkleri yükleniyor...",
    shareLinksLoadFailed: "Paylaşım linkleri getirilemedi.",
    noShareLinks: "Henüz paylaşım linki yok.",
    shareStatusActive: "Aktif",
    shareStatusExpired: "Süresi doldu",
    shareStatusRevoked: "İptal edildi",
    revokeShare: "İptal et",
    revokingShare: "İptal ediliyor...",
    shareRevoked: "Paylaşım linki iptal edildi.",
    shareRevokeFailed: "Paylaşım linki iptal edilemedi.",
    revokeShareTitle: "Paylaşım linkini iptal et",
    revokeShareText:
      "Bu paylaşım linki hemen çalışmayı durduracak. Bu işlem geri alınamaz.",
    revokeShareConfirmButton: "Linki iptal et",
    refreshShareLinks: "Yenile",
    createdAt: "Oluşturuldu",
    path: "Yol",
  },
};
