export const sozluk = {
  en: {
    loginIdentifierPlaceholder: "Username or email",
    registerUsernamePlaceholder: "Username",
    passPlaceholder: "Password",
    connectBtn: "Login",
    registerBtn: "Register Account",
    emailPlaceholder: "Email",
    emailMissing: "Please enter an email address.",
    invalidEmail: "Please enter a valid email address.",
    switchToReg: "Need an account? Register here.",
    switchToLogin: "Already have an account? Login here.",
    srvIp: "Server IP",
    srvUser: "Server User (e.g. root)",
    srvPass: "Server Password",
    folder: "Isolated Folder (e.g. /PionterCloud)",
    currentPath: "Current Path:",
    upFolder: "Up",
    loading: "Processing...",
    emptyFolder: "This folder is empty.",
    dragDrop: "Drag and drop files here",
    orSelect: "or select from your computer",
    selectBtn: "Select File",
    regSuccess: "Registration successful! You can now login.",
    regFail: "Registration failed. Username or email might be taken.",
    myServers: "My Servers",
    serversDraftInfo:
      "We are not saving real servers yet. For now, we are building the screen draft.",
    addServer: "Add Server",
    noServersYet: "No servers added yet.",
    noServersInfo: "In the next task, we will make this form save a server.",
    newServer: "Add New Server",
    serverNickname: "Server Nickname",
    sshUser: "SSH User",
    sshPort: "SSH Port",
    connectWithPassword: "Connect with password",
    connectWithKey: "Connect with SSH key",
    isolatedFolder: "Isolated Folder",
    sshPrivateKey: "SSH Private Key",
    cancel: "Cancel",
    save: "Save",
    saveLater: "We will make the save action work in the next task.",
    loginMissing: "Please enter username and password!",
    selectedServer: "Selected Server",
    backToServers: "Back to Servers",
    newFolderPlaceholder: "New folder name",
    createFolder: "Create Folder",
    deleteItem: "Delete",
    deleteConfirm: "Are you sure you want to delete this item?",
    deleteFailed: "Delete failed.",
    renameItem: "Rename",
    renamePrompt: "Enter the new name:",
    renameFailed: "Rename failed.",
    moveItem: "Move",
    moveFailed: "Move failed.",
    homeFolder: "Home",
    searchPlaceholder: "Search in current folder...",
    noSearchResults: "No matching files or folders found.",
    uploadSuccess: "File uploaded successfully.",
    uploadFailed: "Upload failed.",
    folderCreateSuccess: "Folder created successfully.",
    folderCreateFailed: "Folder could not be created.",
    selectServerFirst: "You must select a server first.",
    invalidFileName: "File name cannot include /, \\, ⁄ or ...",
    folderNameEmpty: "Folder name cannot be empty.",
    invalidFolderName: "Folder name cannot include /, \\, ⁄ or ...",
    invalidTargetPath: "Target path cannot include \\, ⁄ or ...",
    alreadyInThisFolder: "This item is already in that folder.",
    renameModalTitle: "Rename Item",
    newNamePlaceholder: "New name",
    confirmRename: "Rename",
    moveModalTitle: "Move Item",
    targetPathEmpty: "Target folder path cannot be empty.",
    deleteModalTitle: "Delete Item",
    deleteModalText: "Are you sure you want to delete this item?",
    confirmDelete: "Delete",
    serverRequiredFields: "Please fill the required fields.",
    serverPasswordRequired: "Please enter the server password.",
    sshKeyRequired: "Please enter the SSH private key.",
    serverSaveFailed: "Server could not be saved.",
    serverSaveSuccess: "Server saved successfully.",
    invalidServerPort: "SSH port must be a number between 1 and 65535.",
    invalidIsolatedFolder: "Isolated folder must start with /.",
    loadingFiles: "Loading files...",
    uploadingFile: "Uploading file...",
    creatingFolder: "Creating folder...",
    deletingItem: "Deleting item...",
    renamingItem: "Renaming item...",
    movingItem: "Moving item...",
    downloadingFile: "Downloading file...",
    savingServer: "Checking connection and saving server...",
    loadingServers: "Loading servers...",
    registeringAccount: "Creating account...",
    authTitle: "Your own cloud, on your own server.",
    authSubtitle:
      "Add your server and manage your files through a clean web interface.",
    loginTitle: "Welcome back",
    registerTitle: "Create your account",
    loginInfo: "Login with your username or email and password.",
    registerInfo: "Create a Pionter account to start adding your servers.",
    confirmMoveHere: "Move Here",
    currentMoveTarget: "Current target",
    deleteServer: "Delete Server",
    deleteServerTitle: "Delete Server",
    deleteServerText:
      "This will remove the server from PionterCloud. Files on the actual server will not be deleted.",
    deleteServerFailed: "Server could not be deleted.",
    deleteServerSuccess: "Server deleted successfully.",
    deletingServer: "Deleting server...",
    editServer: "Edit",
    editServerTitle: "Edit Server",
    serverCredentialsOptional:
      "Leave the password or SSH key empty to keep the current saved credential.",
    saveServerChanges: "Save Changes",
    serverUpdateSuccess: "Server updated successfully.",
    serverUpdateFailed: "Server could not be updated.",
    updatingServer: "Checking connection and updating server...",
    pinServer: "Pin",
    unpinServer: "Unpin",
    serverPinFailed: "Server pin status could not be updated.",
    pinnedServer: "Pinned",
    testConnection: "Test Connection",
    testingConnection: "Testing connection...",
    connectionTestSuccess: "Connection test successful.",
    connectionTestFailed: "Connection test failed.",
    loggingIn: "Logging in...",
    logout: "Logout",
    loggingOut: "Logging out...",
    logoutSuccess: "Logged out successfully.",
    logoutFailed: "Logout failed.",
    sessionExpired: "Your session has expired. Please log in again.",
    uploadProgress: "Upload",
    multiUploadSuccess: "Files uploaded successfully.",
    selectedItems: "item(s) selected",
    clearSelection: "Clear selection",
    selectItem: "Select item",
    unselectItem: "Unselect item",
    deleteSelected: "Delete selected",
    deleteSelectedTitle: "Delete selected items",
    deleteSelectedConfirmText:
      "Are you sure you want to delete selected item(s)?",
    deletingSelectedItems: "Deleting selected items...",
    selectedItemsDeleted: "Selected items deleted.",
    bulkDeleteFailed: "Selected items could not be deleted.",
    selectListed: "Select listed",
    upload: "Upload",
    dropFilesToUpload: "Drop files to upload",
    releaseMouseToUpload: "Release to start uploading",
    newFolder: "New folder",
    newFolderTitle: "Create new folder",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    darkMode: "Dark mode",
    lightMode: "Light mode",
  },
  tr: {
    loginIdentifierPlaceholder: "Kullanıcı adı veya e-posta",
    registerUsernamePlaceholder: "Kullanıcı adı",
    passPlaceholder: "Şifre",
    connectBtn: "Giriş Yap",
    registerBtn: "Hesap Oluştur",
    emailPlaceholder: "E-posta",
    emailMissing: "Lütfen e-posta adresi gir.",
    invalidEmail: "Lütfen geçerli bir e-posta adresi gir.",
    switchToReg: "Hesabın yok mu? Buradan kayıt ol.",
    switchToLogin: "Zaten hesabın var mı? Buradan giriş yap.",
    srvIp: "Sunucu IP",
    srvUser: "Sunucu Kullanıcısı (Örn: root)",
    srvPass: "Sunucu Şifresi",
    folder: "İzole Klasör (Örn: /PionterCloud)",
    currentPath: "Mevcut Konum:",
    upFolder: "Üst Klasör",
    loading: "İşlem yapılıyor...",
    emptyFolder: "Bu klasör boş.",
    dragDrop: "Dosyaları buraya sürükleyin",
    orSelect: "veya bilgisayarınızdan seçin",
    selectBtn: "Dosya Seç",
    regSuccess: "Kayıt başarılı! Şimdi giriş yapabilirsiniz.",
    regFail: "Kayıt başarısız. Kullanıcı adı veya e-posta alınmış olabilir.",
    myServers: "Sunucularım",
    serversDraftInfo:
      "Henüz gerçek sunucu kaydı yapmıyoruz. Şimdilik ekran taslağını kuruyoruz.",
    addServer: "Sunucu Ekle",
    noServersYet: "Henüz sunucu eklenmedi.",
    noServersInfo:
      "Bir sonraki görevde bu formun sunucu kaydetmesini sağlayacağız.",
    newServer: "Yeni Sunucu Ekle",
    serverNickname: "Sunucu Takma Adı",
    sshUser: "SSH Kullanıcısı",
    sshPort: "SSH Portu",
    connectWithPassword: "Şifre ile bağlan",
    connectWithKey: "SSH Key ile bağlan",
    isolatedFolder: "İzole Klasör",
    sshPrivateKey: "SSH Private Key",
    cancel: "Vazgeç",
    save: "Kaydet",
    saveLater: "Kaydetme işlemini bir sonraki görevde yapacağız.",
    loginMissing: "Kullanıcı adı ve şifre gir!",
    selectedServer: "Seçili Sunucu",
    backToServers: "Sunuculara Dön",
    newFolderPlaceholder: "Yeni klasör adı",
    createFolder: "Klasör Oluştur",
    deleteItem: "Sil",
    deleteConfirm: "Bu öğeyi silmek istediğine emin misin?",
    deleteFailed: "Silme başarısız.",
    renameItem: "Yeniden Adlandır",
    renamePrompt: "Yeni adı gir:",
    renameFailed: "Yeniden adlandırma başarısız.",
    moveItem: "Taşı",
    moveFailed: "Taşıma başarısız.",
    homeFolder: "Home",
    searchPlaceholder: "Mevcut klasörde ara...",
    noSearchResults: "Eşleşen dosya veya klasör bulunamadı.",
    uploadSuccess: "Dosya başarıyla yüklendi.",
    uploadFailed: "Dosya yükleme başarısız.",
    folderCreateSuccess: "Klasör başarıyla oluşturuldu.",
    folderCreateFailed: "Klasör oluşturulamadı.",
    selectServerFirst: "Önce sunucu seçmelisin.",
    invalidFileName: "Dosya adında /, \\, ⁄ veya .. kullanılamaz.",
    folderNameEmpty: "Klasör adı boş olamaz.",
    invalidFolderName: "Klasör adında /, \\, ⁄ veya .. kullanılamaz.",
    invalidTargetPath: "Hedef yolda \\, ⁄ veya .. kullanılamaz.",
    alreadyInThisFolder: "Bu öğe zaten o klasörde.",
    renameModalTitle: "Yeniden Adlandır",
    newNamePlaceholder: "Yeni ad",
    confirmRename: "Yeniden Adlandır",
    moveModalTitle: "Taşı",
    targetPathEmpty: "Hedef klasör yolu boş olamaz.",
    deleteModalTitle: "Sil",
    deleteModalText: "Bu öğeyi silmek istediğine emin misin?",
    confirmDelete: "Sil",
    serverRequiredFields: "Lütfen zorunlu alanları doldur.",
    serverPasswordRequired: "Lütfen sunucu şifresini gir.",
    sshKeyRequired: "Lütfen SSH private key gir.",
    serverSaveFailed: "Sunucu kaydedilemedi.",
    serverSaveSuccess: "Sunucu başarıyla kaydedildi.",
    invalidServerPort: "SSH portu 1 ile 65535 arasında bir sayı olmalı.",
    invalidIsolatedFolder: "İzole klasör / ile başlamalı.",
    loadingFiles: "Dosyalar yükleniyor...",
    uploadingFile: "Dosya yükleniyor...",
    creatingFolder: "Klasör oluşturuluyor...",
    deletingItem: "Öğe siliniyor...",
    renamingItem: "Yeniden adlandırılıyor...",
    movingItem: "Öğe taşınıyor...",
    downloadingFile: "Dosya indiriliyor...",
    savingServer: "Bağlantı kontrol ediliyor ve sunucu kaydediliyor...",
    loadingServers: "Sunucular yükleniyor...",
    registeringAccount: "Hesap oluşturuluyor...",
    authTitle: "Kendi sunucun, kendi bulutun.",
    authSubtitle: "Sunucunu ekle ve dosyalarını sade bir web arayüzüyle yönet.",
    loginTitle: "Tekrar hoş geldin",
    registerTitle: "Hesabını oluştur",
    loginInfo: "Kullanıcı adın veya e-postan ve şifrenle giriş yap.",
    registerInfo: "Sunucularını eklemeye başlamak için Pionter hesabı oluştur.",
    confirmMoveHere: "Buraya Taşı",
    currentMoveTarget: "Geçerli hedef",
    deleteServer: "Sunucuyu Sil",
    deleteServerTitle: "Sunucuyu Sil",
    deleteServerText:
      "Bu işlem sunucuyu PionterCloud listesinden kaldırır. Gerçek sunucudaki dosyalar silinmez.",
    deleteServerFailed: "Sunucu silinemedi.",
    deleteServerSuccess: "Sunucu başarıyla silindi.",
    deletingServer: "Sunucu siliniyor...",
    editServer: "Düzenle",
    editServerTitle: "Sunucuyu Düzenle",
    serverCredentialsOptional:
      "Kayıtlı bilgiyi korumak için sunucu şifresini veya SSH key alanını boş bırakabilirsin.",
    saveServerChanges: "Değişiklikleri Kaydet",
    serverUpdateSuccess: "Sunucu başarıyla güncellendi.",
    serverUpdateFailed: "Sunucu güncellenemedi.",
    updatingServer: "Bağlantı kontrol ediliyor ve sunucu güncelleniyor...",
    pinServer: "Sabitle",
    unpinServer: "Kaldır",
    serverPinFailed: "Sunucu sabitleme durumu güncellenemedi.",
    pinnedServer: "Sabitli",
    testConnection: "Bağlantıyı Test Et",
    testingConnection: "Bağlantı test ediliyor...",
    connectionTestSuccess: "Bağlantı testi başarılı.",
    connectionTestFailed: "Bağlantı testi başarısız.",
    loggingIn: "Giriş yapılıyor...",
    logout: "Çıkış Yap",
    loggingOut: "Çıkış yapılıyor...",
    logoutSuccess: "Çıkış yapıldı.",
    logoutFailed: "Çıkış yapılamadı.",
    sessionExpired: "Oturum süren doldu. Lütfen tekrar giriş yap.",
    uploadProgress: "Yükleme",
    multiUploadSuccess: "Dosyalar yüklendi.",
    selectedItems: "öğe seçildi",
    clearSelection: "Seçimi temizle",
    selectItem: "Öğeyi seç",
    unselectItem: "Seçimi kaldır",
    deleteSelected: "Seçilenleri sil",
    deleteSelectedTitle: "Seçili öğeleri sil",
    deleteSelectedConfirmText: "Seçili öğeleri silmek istediğine emin misin?",
    deletingSelectedItems: "Seçili öğeler siliniyor...",
    selectedItemsDeleted: "Seçili öğeler silindi.",
    bulkDeleteFailed: "Seçili öğeler silinemedi.",
    selectListed: "Listelenenleri seç",
    upload: "Yükle",
    dropFilesToUpload: "Yüklemek için dosyaları bırak",
    releaseMouseToUpload: "Yüklemeyi başlatmak için bırak",
    newFolder: "Yeni klasör",
    newFolderTitle: "Yeni klasör oluştur",
    settings: "Ayarlar",
    language: "Dil",
    theme: "Tema",
    darkMode: "Koyu mod",
    lightMode: "Açık mod",
  },
};
